[build]
command = "npm install && npm --prefix backend install --omit=dev && npm --prefix frontend install && npm --prefix frontend run build"
  publish = "./dist"

[functions]
  directory = "./netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
